-- P04 seed placeholder.
-- After adding content/taxonomy/csec_2027_taxonomy_seed.json, run:
--   node scripts/gen-taxonomy-seed.mjs
-- Then uncomment the lines below (or replace this file).
--
-- \ir seed/01_syllabus_v2027.sql
-- \ir seed/02_topics.sql
-- \ir seed/03_specific_objectives.sql
-- \ir seed/04_skills.sql
