-- Generated by scripts/gen-taxonomy-seed.js — do not edit by hand
begin;

insert into public.subjects (code, name, is_active, sequence) values (
  'CSEC_MATH',
  'CSEC Mathematics',
  true,
  0
) on conflict (code) do update set
  name = excluded.name,
  is_active = excluded.is_active,
  sequence = excluded.sequence;

insert into public.syllabus_versions (
  code, subject_code, official_code, effective_from_year, effective_from_month,
  has_modules, is_default, source_document
) values (
  'V2027'::public.syllabus_code,
  'CSEC_MATH',
  'CXC 05/G/SYLL 16',
  2027,
  'may_june'::public.sitting_month,
  true,
  true,
  'CSEC_Mathematics_Syllabus_2027.pdf'
) on conflict (code) do update set
  subject_code = excluded.subject_code,
  official_code = excluded.official_code,
  effective_from_year = excluded.effective_from_year,
  effective_from_month = excluded.effective_from_month,
  has_modules = excluded.has_modules,
  is_default = excluded.is_default,
  source_document = excluded.source_document;

insert into public.modules (
  syllabus_code, module_no, name, paper01_items, paper02_marks, weighted_marks, duration_hours
) values (
  'V2027'::public.syllabus_code,
  1,
  'Fundamentals of Secondary Level Mathematics',
  20,
  30,
  100,
  65
) on conflict (syllabus_code, module_no) do update set
  name = excluded.name,
  paper01_items = excluded.paper01_items,
  paper02_marks = excluded.paper02_marks,
  weighted_marks = excluded.weighted_marks,
  duration_hours = excluded.duration_hours;

insert into public.modules (
  syllabus_code, module_no, name, paper01_items, paper02_marks, weighted_marks, duration_hours
) values (
  'V2027'::public.syllabus_code,
  2,
  'Intermediate Secondary Level Mathematics',
  20,
  30,
  100,
  65
) on conflict (syllabus_code, module_no) do update set
  name = excluded.name,
  paper01_items = excluded.paper01_items,
  paper02_marks = excluded.paper02_marks,
  weighted_marks = excluded.weighted_marks,
  duration_hours = excluded.duration_hours;

insert into public.modules (
  syllabus_code, module_no, name, paper01_items, paper02_marks, weighted_marks, duration_hours
) values (
  'V2027'::public.syllabus_code,
  3,
  'Higher Concepts in Secondary Level Mathematics',
  20,
  30,
  100,
  65
) on conflict (syllabus_code, module_no) do update set
  name = excluded.name,
  paper01_items = excluded.paper01_items,
  paper02_marks = excluded.paper02_marks,
  weighted_marks = excluded.weighted_marks,
  duration_hours = excluded.duration_hours;

commit;
