-- Generated by scripts/gen-taxonomy-seed.js — do not edit by hand
begin;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  1,
  'M1-T1',
  'Number Theory and Computation',
  1,
  4,
  'Number Theory and Computation / Consumer Arithmetic',
  null,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 1
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  2,
  'M1-T2',
  'Consumer Arithmetic',
  2,
  4,
  'Number Theory and Computation / Consumer Arithmetic',
  null,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 1
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  3,
  'M1-T3',
  'Sets',
  3,
  3,
  'Graphs, Sets, Measurement, Algebra 1',
  3,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 1
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  4,
  'M1-T4',
  'Measurement',
  4,
  4,
  'Graphs, Sets, Measurement, Algebra 1',
  3,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 1
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  5,
  'M1-T5',
  'Algebra 1',
  5,
  3,
  'Graphs, Sets, Measurement, Algebra 1',
  3,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 1
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  6,
  'M1-T6',
  'Introduction to Graphs',
  6,
  2,
  'Graphs, Sets, Measurement, Algebra 1',
  3,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 1
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  1,
  'M2-T1',
  'Statistics 1',
  1,
  4,
  'Statistics 1',
  6,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 2
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  2,
  'M2-T2',
  'Algebra 2',
  2,
  4,
  'Algebra 2 / Relations, Functions and Graphs 1',
  6,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 2
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  3,
  'M2-T3',
  'Relations, Functions and Graphs 1',
  3,
  4,
  'Algebra 2 / Relations, Functions and Graphs 1',
  6,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 2
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  4,
  'M2-T4',
  'Geometry and Trigonometry 1',
  4,
  4,
  'Geometry and Trigonometry 1',
  9,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 2
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  5,
  'M2-T5',
  'Vectors and Matrices 1',
  5,
  4,
  'Vectors and Matrices 1',
  3,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 2
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  1,
  'M3-T1',
  'Statistics 2',
  1,
  4,
  'Statistics 2',
  6,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 3
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  2,
  'M3-T2',
  'Relations, Functions and Graphs 2',
  2,
  6,
  'Relations, Functions and Graphs 2',
  6,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 3
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  3,
  'M3-T3',
  'Geometry and Trigonometry 2',
  3,
  6,
  'Geometry and Trigonometry 2',
  9,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 3
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

insert into public.topics (
  syllabus_code, module_id, topic_no, code, name, sequence,
  paper01_items, paper02_marks_group, paper02_marks, is_active
)
select
  'V2027'::public.syllabus_code,
  m.id,
  4,
  'M3-T4',
  'Vectors and Matrices 2',
  4,
  4,
  'Vectors and Matrices 2',
  9,
  true
from public.modules m
where m.syllabus_code = 'V2027'::public.syllabus_code
  and m.module_no = 3
on conflict (syllabus_code, code) do update set
  module_id = excluded.module_id,
  topic_no = excluded.topic_no,
  name = excluded.name,
  sequence = excluded.sequence,
  paper01_items = excluded.paper01_items,
  paper02_marks_group = excluded.paper02_marks_group,
  paper02_marks = excluded.paper02_marks,
  is_active = excluded.is_active;

commit;
